### ISSUE TITLE
Duplicate photo and source tags

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#105]
Task 3248 is a repetition of a previously tagged photo.http://geotagx.org/project/yemenculture/task/3248
Is there a way I can check those that I have tagged and submitted. When I find the duplicate, it is not always immediately after. The task list that I downloaded does not help to indicate which photo was similar if it points to a page of photos. This is the case of the photos from the rgs project.
The source link is quite long then... 

http://images.rgs.org/search.aspx?view=&search_ctl%3Akeyword=yemen&search_ctl%3Aimage_type_list=0&search_ctl%3Acollection_list=-1&search_ctl%3AimageSubmit.x=0&search_ctl%3AimageSubmit.y=0&search_ctl%3Adate_range_list=0&search_ctl%3AregionEvent=0&search_ctl%3AdropdownThemes=0&search_ctl%3AsearchPhotographOrPersonShown%3A0=on&search_ctl%3AsearchPhotographOrPersonShown%3A1=on&search_ctl%3Arefine_keyword_field=&isAdvancedSearchDisplay=&search_ctl%3Acollection_choosed=&search_ctl%3AisButtongotoPressed=no

The link to the image page is
http://images.rgs.org/search.aspx?view=&search_ctl%3Akeyword=yemen&search_ctl%3Aimage_type_list=0&search_ctl%3Acollection_list=-1&search_ctl%3AimageSubmit.x=0&search_ctl%3AimageSubmit.y=0&search_ctl%3Adate_range_list=0&search_ctl%3AregionEvent=0&search_ctl%3AdropdownThemes=0&search_ctl%3AsearchPhotographOrPersonShown%3A0=on&search_ctl%3AsearchPhotographOrPersonShown%3A1=on&search_ctl%3Arefine_keyword_field=&isAdvancedSearchDisplay=&search_ctl%3Acollection_choosed=&search_ctl%3AisButtongotoPressed=no

And the "actual image" itself is
http://images.rgs.org/webimages/0/0/10000/3000/200/S0013271_thumb.jpg

Can the source link be made more precise?

**Comment by elliec** [comment]
@tagapic PyBossa displays the tasks in numerical order, in theory you have probably looked at most images in the yemen project with task ids <3248. I think the way to check if something has been duplicated would be to search for the image url http://images.rgs.org/webimages/0/0/10000/3000/200/S0013271_thumb.jpg in the task list you have downloaded.

The source url is extracted automatically from the page on which the photo was found so we don't have any control really over how it looks. I think too that that long url is the only way to get to the page on which the photo was found because it is a search result page

Ellie

**Comment by tagapic** [comment]
@elliec thank you, since the excel file links only to the page (or to 1 of several pages) and not to the image (in the rgs project), I could not find the image url. Is it at all possible to have a thumbnail of the image in the excel?

**Comment by elliec** [comment]
@tagapic I don't think we can do that in the excel, but we could possibly do that on the browse tasks page

Action: Add thumbnail of photo and image source to browse task page

**Comment by elliec** [comment]
closing - see #125 for action
