### ISSUE TITLE
Ebola Project: question regarding "wearing all recommended protective equipment" - 

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#114]
<b>Task 605 Image 12/104</b> The image shows health worker wearing protective equipment. However, the photo is waist up so one cannot say anything about shoes. One has to assume that the person is wearing protective shoes. Responding as "Yes".

**Comment by elliec** [comment]
In this case you can select "I don't know" because it is not possible to answer the question given the photo that you can see. Along with this you could also put a comment in the comments section for that photo (see "show comments" under the question) with what you have mentioned in this issue. 

I think the improvement you suggest in #116 are needed in this case - the question and/or help needs to be clearer so the analysts know what they are answering.

**Comment by tagapic** [comment]
thanks @elliec, wondering if it could be made possible to skip a question like this where you may want to raise an issue rather than just answer something and then come back to the skipped ones. Perhaps all of this can be taken up in the review....
