### ISSUE TITLE
information on categories missing

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#16]
The information about each category is important, can we display it somewhere when people click on a category?

**Comment by spMohanty** [comment]
@elliec : Now on double clicking on the category anchors on the front page, you can go to the category page. (There is a tooltip which lets the user what happens when you double click or do a single click on the icon)

~~TO-DO :: Render project tiles to be consistent with the rest of the theme.~~

Let me know, if this is what you had in mind,

**Comment by elliec** [comment]
@spMohanty Looks fine, this can be closed if you've done your TO-DO from the last comment
