### ISSUE TITLE
password recovery doesnt work

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#34]
maybe we need to enable emails from the server?

**Comment by spMohanty** [comment]
(Not sure where exactly to put this issue, so will leave it here for the timebeing until we have an issue tracker for systems-administration related stuff)

This issue has been fixed, and for future reference :: this was because the `rq worker` process had crashed silently for some reason on the server.
To fix that, I configured `supervisor` and aggregated together a few scripts which will now deal with starting the `rq scheduler` and the `rq worker`. `supervisor` will make sure that these processes are running at all times.
