### ISSUE TITLE
automatically update categories on homepage when changed by admin

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#76]
Categories on homepage have to be manually updated by developer, this should be made automatic. Needs to be done by friday in prep for release of Yemen project

**Comment by spMohanty** [comment]
@elliec : Fixed !! But if you add more categories, then they get added in a separate row, and surprisingly it doesn't really look that bad !! 
(Any changes to the categories take a ~~few minutes~~ **a day** to take effect, as all the data on the front page is cached for reasons related to performance)

Update : On a closer look, the default Category Cache timeout is 24 hours. If you want any changes to reflect urgently, you can simply edit the `CATEGORY_TIMEOUT` value to `1` instead of `24 * 60 * 60`  in `/home/pybossa/new_geotagx/pybossa/pybossa/default_settings.py` and then restart the server using `/etc/init.d/apache2 restart` , then refresh the page a few times till you see the changes, and then revert back the `CATEGORY_TIMEOUT` value and restart the server again.

**Comment by elliec** [comment]
@spMohanty great thanks! I will leave this open until i am able to test it to see how it works, will let you know how i go
