### ISSUE TITLE
add function to email all users from admin interface

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#83]

**Comment by elliec** [comment]
@spMohanty can this be done in the next day or two?

**Comment by spMohanty** [comment]
@elliec : Can you let me know what the reply address for the email should be ? usually its "noreply@geotagx.org". 

Should I use the geotagx@cern.ch email address as reply address for the email ?

**Comment by elliec** [comment]
@spMohanty you can use that, however im not sure I will use this for messages that need replying. I think its better to leave the no reply and if i have to i can mention in the email how they can contact us if need-be

**Comment by spMohanty** [comment]
Implemented in the commits : https://github.com/geotagx/pybossa/commit/dabf1f142600fbc00bd78185fb9e0a056a51bdee , https://github.com/geotagx/pybossa/commit/7c0057ff107d11d298c3beb64f5a901a26547617 , https://github.com/geotagx/geotagx-theme/commit/29eb5eecd2619cd32401d780d9ef5e87180af7fc ) 

(Copying contents from our email on this thread, so that it can be used as reference in the future)
@elliec : You can now send a newsletter using this interface : http://geotagx.org/geotagx/newsletter
(Can access the link through the Admin site)

It has something called as the `Debug Mode`. When it is checked, it sends the email to the list of recipients configured in the `GEOTAGX_NEWSLETTER_DEBUG_EMAIL_LIST` in `settings_local.py` file.
(Note: If you change any keys in `settings_local.py`, it is always advisable to restart the server to make sure the new changes take effect. You can restart the server by `/etc/init.d/apache2 restart` )

If you uncheck the `Debug Mode`, then it sends an email to all the users of the site. Have not tested sending out newsletters to **all** the users. But should work in principle. Give it a go, and let me know if there are any glitches.
